### ISSUE TITLE
Install with directory can't find missing Git submodule directory

### ISSUE THREAD

**Issue by dmwelch** [int64ago/node-reveal#2]
When I try to create a new project with directory:
$ reveal -i outdir
```
fs.js:948
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '/Users/dwelc/.nvm/versions/node/v8.11.4/lib/node_modules/node-reveal/reveal.js'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (/Users/dwelc/.nvm/versions/node/v8.11.4/lib/node_modules/node-reveal/node_modules/graceful-fs/polyfills.js:297:22)
    at copySync (/Users/dwelc/.nvm/versions/node/v8.11.4/lib/node_modules/node-reveal/node_modules/fs-extra/lib/copy-sync/copy-sync.js:31:86)
    at init (/Users/dwelc/.nvm/versions/node/v8.11.4/lib/node_modules/node-reveal/src/handler.js:42:3)
    at module.exports (/Users/dwelc/.nvm/versions/node/v8.11.4/lib/node_modules/node-reveal/src/handler.js:65:3)
    at Object.<anonymous> (/Users/dwelc/.nvm/versions/node/v8.11.4/lib/node_modules/node-reveal/index.js:30:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

It looks like the submodule isn't getting initialized with `npm i node-reveal -g`.  Doing an `ls -a` on the node-reveal directory doesn't show a `reveal.js` file OR a `.git/` directory (so `git submodule init` fails): 
`.  ..  .gitmodules Dockerfile  LICENSE  README.md  assets  index.js  node_modules  package.json  src  template`

SOLUTION:

``` sh
$ cd ~/.nvm/versions/node/v8.11.4/lib/node_modules/node-reveal
$ git clone https://github.com/hakimel/reveal.js.git reveal.js
```

**Comment by int64ago** [comment]
#3
