### ISSUE TITLE
Empty path (not default 'reveal-demo') passed to install

### ISSUE THREAD

**Issue by dmwelch** [int64ago/node-reveal#3]
When I try to install without a directory given:

$ reveal -i
```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received true
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at init (/Users/dwelc/.nvm/versions/node/v8.11.4/lib/node_modules/node-reveal/src/handler.js:29:25)
    at module.exports (/Users/dwelc/.nvm/versions/node/v8.11.4/lib/node_modules/node-reveal/src/handler.js:65:3)
    at Object.<anonymous> (/Users/dwelc/.nvm/versions/node/v8.11.4/lib/node_modules/node-reveal/index.js:30:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by int64ago** [comment]
Hi, sorry for this, i made a mistake during previous publish, i republished, please run `npm i node-reveal -g` and try again.
